version: '3.8'

services:
  frontend:
    build:
      context: ./front
    ports:
      - "8082:80"
    networks:
      - app-network

  backend:
    build:
      context: ./server
    expose:
      - "8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge